version: "3"
services:
  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    hostname: spark-master
    container_name: spark-master
    ports:
      - "18080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    hostname: spark-worker-1
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-thriftserver:
    build: 
      context: ..
      args:
        - "SPARK_VERSION=3.0.1-hadoop3.2"
    hostname: spark-thriftserver
    container_name: spark-thriftserver
    depends_on:
      - spark-master
    ports: 
      - "10000:10000"
    environment:
      - "SPARK_MASTER=spark-master:7077"
